### ISSUE TITLE
null object converted to string

### ISSUE THREAD

**Issue by navi86** [hashicorp/terraform-provider-kubernetes-alpha#207]
Terraform version: v0.12.26
Provider version: 0.2.1
Kubernetes version: v1.19.7
```

### Affected Resource(s)
<!-- Please list the resources as a list, for example:
- custom_resource
- opc_storage_volume
If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this. -->

### Terraform Configuration Files
```hcl
resource "kubernetes_manifest" "application" {
  provider = kubernetes-alpha

  manifest = {
    "apiVersion" = "argoproj.io/v1alpha1"
    "kind"       = "Application"
    "metadata" = {
      "name"      = "test-app"
      "namespace" = "test"
    }
    "spec" = {
      "destination" = {
        "namespace" = "test-app"
        "name"      = "gke-app-dev-1"
      }
      "project" = var.application.name
      "source" = {
        "path"           = "test-app"
        "repoURL"        = "https://myrepo.git"
        "targetRevision" = "HEAD"
      }
      "syncPolicy" = {
        "automated" = (contains(["dev", "test"], "dev")  ? null : {}
        "syncOptions" = [
          "CreateNamespace=false",
        ]
      }
    }
  }
}
```

### Debug Output
`Error: rpc error: code = Unknown desc = update dry-run for 'argo/test-app' failed: Application.argoproj.io "test-app" is invalid: spec.syncPolicy.automated: Invalid value: "null": spec.syncPolicy.automated in body must be of type object: "null"`

### Steps to Reproduce
terraform plan

### Expected Behavior
What should have happened?
value should be null, not "null"
### Actual Behavior
What actually happened?
value is "null"

**Comment by alexsomesan** [comment]
Hi @navi86 !

A few observations first. You are using quite old provider and Terraform versions.

Firstly, provider version 0.2.1 is outdated and we've made substantial improvements in recent versions. At this point in time, provider version 0.2.1 should be considered obsolete.
Secondly, according to the [README, the minimum Terraform version](https://github.com/hashicorp/terraform-provider-kubernetes-alpha#requirements) needed for recent provider versions is 0.14.8

I tested the manifest you provided and ran into some syntax issues. You are missing the last closing parenthesis in this expression:
` (contains(["dev", "test"], "dev")  ? null : {}` 
Once I added the missing parenthesis I was able to apply the example successfully.

My suggestion is to upgrade to the latest provider version and try this again.
I will close this since there is nothing to address in the provider for this issue, but feel free to re-open if you're still running into issues with the latest provider version.
