### ISSUE TITLE
Publish alpha provider to Terraform Registry

### ISSUE THREAD

**Issue by AndrewDryga** [hashicorp/terraform-provider-kubernetes-alpha#58]
### Description

Hey guys,

Thank you for your awesome work 🎊. 

One thing that can simplify battle testing this is publishing alpha provider to https://registry.terraform.io/ so that it's easier to start using it by teams of developers (otherwise everyone on a team would need to unzip provider to terraform plugins directory which complicates things a lot). I think as soon as a couple bugs are fixed we will be ready to migrate our YAML configuration and start running this provider in a staging environment.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexsomesan** [comment]
Hi @AndrewDryga,

Due to the alpha state of this provider, we decided not to publish it to the registry so it would not inadvertently be used in critical scenarios without the user being aware of it's current limitations.

Once we pass the initial validation and we improve on a few critical bugs and missing features we will either publish it to the registry or merge it an extension to the current official Kubernetes provider.

**Comment by WilliamABradley** [comment]
Does the changes to the Registry in Terraform 0.13 make this easier?

**Comment by jcmcken** [comment]
Is there an ETA or roadmap? I really hope this doesn't become like Terraform 0.12 where it was in alpha/beta for seemingly (or maybe even literally, I don't actually recall) 3 years.

Personally, to me, having 'alpha' in the provider name is a clear indication that the buyer should beware. We're using TFE, and the fact it's not in the registry makes it difficult for us to even begin smoketesting this to provide feedback. I think the fastest and clearest way to get feedback is to publish the module so that it's easy to use.

**Comment by aareet** [comment]
```
❯ t init

Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/kubernetes-alpha versions matching "0.2.0"...
- Installing hashicorp/kubernetes-alpha v0.2.0...
- Installed hashicorp/kubernetes-alpha v0.2.0 (signed by HashiCorp)


Warning: Additional provider information from registry

The remote registry returned warnings for
registry.terraform.io/hashicorp/kubernetes-alpha:
- Please do not rely on this provider for production use while we strive
towards project maturity.
https://github.com/hashicorp/terraform-provider-kubernetes-alpha#experimental-status

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```
🙌 🥳

**Comment by aareet** [comment]
The alpha provider is now available in the registry: https://registry.terraform.io/providers/hashicorp/kubernetes-alpha/latest
