### ISSUE TITLE
Support load_config_file argument

### ISSUE THREAD

**Issue by JesterOrNot** [hashicorp/terraform-provider-kubernetes-alpha#82]
### Description

Support load_config_file in the Kubernetes provider you can opt not to reference a Kubeconfig file like so

```hcl
# https://www.terraform.io/docs/providers/kubernetes/index.html
provider "kubernetes" {
  host                   = aws_eks_cluster.gitpod.endpoint
  cluster_ca_certificate = base64decode(aws_eks_cluster.gitpod.certificate_authority.0.data)
  token                  = data.aws_eks_cluster_auth.default.token
  load_config_file       = false
}
```

As of right now I need to specify a config file or you get an rpc error:

```log
Error: rpc error: code = Unknown desc = cannot load Kubernetes client config: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
```

However, I use Terraform to provision my cluster and the provider tries to initialize before the local-exec provisioner I use to update the kubernetes config

```hcl
provisioner "local-exec" {
  command = "aws eks update-kubeconfig --name ${var.kubernetes.cluster-name}"
}
```

I tried an explicit `depends_on` but it did not work as it is reserved

### Potential Terraform Configuration

```hcl
# https://www.terraform.io/docs/providers/kubernetes/index.html
provider "kubernetes-alpha" {
  host                   = aws_eks_cluster.gitpod.endpoint
  cluster_ca_certificate = base64decode(aws_eks_cluster.gitpod.certificate_authority.0.data)
  token                  = data.aws_eks_cluster_auth.default.token
  load_config_file       = false
}
```

### References

n/a

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexsomesan** [comment]
@JesterOrNot The alpha provider already behaves like you describe without the need for `load_config_file`. It will not try to load any external config if you don't set any valid path on `config_path` which is equivalent to setting `load_config_file` to false. It's described here in more detail: https://github.com/hashicorp/terraform-provider-kubernetes-alpha/blob/master/docs/usage.md#credentials

The issue you are seeing is caused by the fact that the cluster is created in the same apply operation. It should improve when PR #65 is released (in a couple of days).

**Comment by JesterOrNot** [comment]
Good to know! Thanks!
